
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import entity.CommercialProduit;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GC_WS", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GCWS {


    /**
     * 
     * @param codePdt
     * @param client
     * @param dateCmd
     * @param qteCmd
     * @param codeCmd
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajouterCommande", targetNamespace = "http://service/", className = "service.AjouterCommande")
    @ResponseWrapper(localName = "ajouterCommandeResponse", targetNamespace = "http://service/", className = "service.AjouterCommandeResponse")
    @Action(input = "http://service/GC_WS/ajouterCommandeRequest", output = "http://service/GC_WS/ajouterCommandeResponse")
    public boolean ajouterCommande(
        @WebParam(name = "codeCmd", targetNamespace = "")
        int codeCmd,
        @WebParam(name = "client", targetNamespace = "")
        String client,
        @WebParam(name = "codePdt", targetNamespace = "")
        int codePdt,
        @WebParam(name = "qteCmd", targetNamespace = "")
        int qteCmd,
        @WebParam(name = "dateCmd", targetNamespace = "")
        XMLGregorianCalendar dateCmd);

    /**
     * 
     * @return
     *     returns java.util.List<service.Produit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduits", targetNamespace = "http://service/", className = "service.GetProduits")
    @ResponseWrapper(localName = "getProduitsResponse", targetNamespace = "http://service/", className = "service.GetProduitsResponse")
    @Action(input = "http://service/GC_WS/getProduitsRequest", output = "http://service/GC_WS/getProduitsResponse")
    public List<CommercialProduit> getProduits();

}
