
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GestionCommercialServiceService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8585/GestionCommercialService?wsdl")
public class GestionCommercialServiceService
    extends Service
{

    private final static URL GESTIONCOMMERCIALSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException GESTIONCOMMERCIALSERVICESERVICE_EXCEPTION;
    private final static QName GESTIONCOMMERCIALSERVICESERVICE_QNAME = new QName("http://service/", "GestionCommercialServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8585/GestionCommercialService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONCOMMERCIALSERVICESERVICE_WSDL_LOCATION = url;
        GESTIONCOMMERCIALSERVICESERVICE_EXCEPTION = e;
    }

    public GestionCommercialServiceService() {
        super(__getWsdlLocation(), GESTIONCOMMERCIALSERVICESERVICE_QNAME);
    }

    public GestionCommercialServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONCOMMERCIALSERVICESERVICE_QNAME, features);
    }

    public GestionCommercialServiceService(URL wsdlLocation) {
        super(wsdlLocation, GESTIONCOMMERCIALSERVICESERVICE_QNAME);
    }

    public GestionCommercialServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONCOMMERCIALSERVICESERVICE_QNAME, features);
    }

    public GestionCommercialServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionCommercialServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GCWS
     */
    @WebEndpoint(name = "GC_WSPort")
    public GCWS getGCWSPort() {
        return super.getPort(new QName("http://service/", "GC_WSPort"), GCWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GCWS
     */
    @WebEndpoint(name = "GC_WSPort")
    public GCWS getGCWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "GC_WSPort"), GCWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONCOMMERCIALSERVICESERVICE_EXCEPTION!= null) {
            throw GESTIONCOMMERCIALSERVICESERVICE_EXCEPTION;
        }
        return GESTIONCOMMERCIALSERVICESERVICE_WSDL_LOCATION;
    }

}
